### ISSUE TITLE
panic during fingerprint

### ISSUE THREAD

**Issue by vulogov** [shellrow/netscan#4]
This code (actually copied from sample) caused panic

The code

`match Fingerprinter::new(src_addr) {
                        Ok(mut scanner) => {
                            scanner.set_wait_time(Duration::from_millis(200));
                            let dst: ProbeTarget = ProbeTarget {
                                ip_addr: dst_addr,
                                open_tcp_ports: vec![22,80],
                                closed_tcp_port: 443,
                                open_udp_port: 123,
                                closed_udp_port: 33455,
                            };
                            scanner.add_probe_target(dst);
                            scanner.set_full_probe();
                            let results = scanner.probe();
                            println!("{:?}", &results);
                        }
                        Err(err) => {
                            let msg = format!("net::scan::fingerprint error: {}", err);
                            log::error!("{}", &msg);
                            return Err(msg.into());
                       }
 }`

The panic

`thread 'main' panicked at 'Failed to create channel No such file or directory (os error 2)', /Users/vulogov/.cargo/registry/src/github.com-1ecc6299db9ec823/default-net-0.11.0/src/gateway/unix.rs:21:19
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: default_net::gateway::unix::get_default_gateway
             at /Users/vulogov/.cargo/registry/src/github.com-1ecc6299db9ec823/default-net-0.11.0/src/gateway/unix.rs:21:19
   3: default_net::interface::unix::interfaces
             at /Users/vulogov/.cargo/registry/src/github.com-1ecc6299db9ec823/default-net-0.11.0/src/interface/unix.rs:64:27
   4: default_net::interface::get_interfaces
             at /Users/vulogov/.cargo/registry/src/github.com-1ecc6299db9ec823/default-net-0.11.0/src/interface/mod.rs:174:5
   5: default_net::gateway::get_default_gateway
             at /Users/vulogov/.cargo/registry/src/github.com-1ecc6299db9ec823/default-net-0.11.0/src/gateway/mod.rs:35:38
   6: netscan_os::fingerprinter::Fingerprinter::new
             at /Users/vulogov/.cargo/registry/src/github.com-1ecc6299db9ec823/netscan-os-0.13.0/src/fingerprinter.rs:61:38
   7: tsak::stdlib::net::scan::fingerprint_host
             at ./src/stdlib/net/scan.rs:38:27`

**Comment by shellrow** [comment]
Thanks for the report. I apologize for the delay in my response.

From the provided logs, it seems that the code was executed on macOS...? 
It appears that the issue you encountered stemmed from the interaction between `netscan` and an older version of `default-net` (v0.11.0), which had a bug related to obtaining the default gateway. 

I am also the owner of the `default-net`.
And inform you that this issue has been addressed and resolved. The bug in obtaining the default gateway present in default-net v0.11.0 has been rectified in subsequent versions.
